### ISSUE TITLE
Where is the object counter codes?

### ISSUE THREAD

**Issue by wuba-pat** [makjac/Traffic_Car_Counter_cpp_openCV_YOLOv3#1]
Hello author,

Could you please tell me there the object(car) counter codes is?

 It seems that your main.cpp codes doesn't contain this part.

**Comment by makjac** [comment]
Hello,

Thank you for your inquiry.

The object (car) counting functionality has been added to the `main_counter.cpp` file. Please note that this code is based on an my external source and has not been thoroughly tested in the current environment.

**Comment by wuba-pat** [comment]
Thank you, I will try it
